-- 코드를 입력하세요
SELECT B.WRITER_ID, F.NICKNAME, CONCAT(F. CITY, ' ', F.STREET_ADDRESS1,' ', F.STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTRING(F.TLNO, 1, 3), '-', SUBSTRING(F.TLNO, 4, 4), '-', SUBSTRING(F.TLNO, 8)) AS 전화번호
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER F ON B.WRITER_ID = F.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY WRITER_ID DESC